log:
  level: WARN
accessLog: {}

global:
  checkNewVersion: true
  sendAnonymousUsage: false

providers:
  docker:
    exposedByDefault: false
  file:
      directory: /etc/traefik/dynamic
      watch: true

api:
  dashboard: true

serversTransport:
  insecureSkipVerify: true

entryPoints:
  web:
    address: :80